User.create(username: 'Abed', email: 'abed@greendale.com', password: 'password', password_confirmation: 'password')
User.create(username: 'Troy', email: 'troy@greendale.com', password: 'password', password_confirmation: 'password')
User.create(username: 'Jake', email: 'awesome@gsauce.com', password: 'password', password_confirmation: 'password')

User.first.maps.create(starting_room_id: 1, title: 'Dreamatorium', description: 'Where we play Professor Spacetime and make dreams come true. Come join us!')
User.first.maps.create(starting_room_id: 1, title: 'Study Room', description: 'Where we admire Annie')
User.first.maps.create(starting_room_id: 1, title: "Neal's' Ocean Adventure" , description: 'Yarr Billy! Sail the seven seas on this swashbuckling adventure!')
User.first.maps.create(starting_room_id: 1, title: "Eric's Romp through History", description: 'Explore the wild, live the childrens crusade, wide world of Arab culture in the late BC')
User.first.maps.create(starting_room_id: 1, title: "Diana's Dream Destroyer", description: 'Create wars, destroy dreams, raze the world.')
User.first.maps.create(starting_room_id: 1, title: "Lauren's Collosal Cavern Exploration", description: 'Explore caves in this classic, 1970s adventure through console-based amazingness.')
User.first.maps.create(starting_room_id: 1, title: "Jay's Music Lounge", description: 'Listen to guitar.  Do drugs.')
User.first.maps.create(starting_room_id: 1, title: "Andrew's T-shirt Emporium", description: 'Save shirts, escape wildfires.')
User.first.maps.create(starting_room_id: 1, title: "Matt's Freight Train Escapade", description: 'Just freight train through all the shit.')
User.first.maps.create(starting_room_id: 1, title: "Alex's Journey through Eastern Europe", description: "Just kidding, he's going to break you")
User.first.maps.create(starting_room_id: 1, title: "Dusty's Debate Team", description: 'Make a statement, end up in a debate')
User.first.maps.create(starting_room_id: 1, title: "Dragon Blaster", description: 'Blast Dragons, Kill Andrew with a dull bowling pin, Dick Maps, Save the Princess')

Game.create(player_id: 1, map_id: 1, room_id: 1, hero_id: 1)
Hero.create(player_id: 1, name: 'Troy', description: 'We miss you')


Game.create(player_id: 1, map_id: 1, room_id: 1, hero_id: 1)
Hero.create(player_id: 1, name: 'Professor Solorio', description: 'AJAX Master')
Room.create(map_id: 12, title: 'Cave Opening', description: 'You see a cave opening.', north_id: nil, south_id: 6, east_id: 2, west_id: nil)
Room.create(map_id: 12, title: 'Old Mansion', description: 'You see an old mansion.', north_id: nil, south_id: 7, east_id: 3, west_id: 1)
Room.create(map_id: 12, title: 'Forest', description: 'You see a forest.', north_id: nil, south_id: 8, east_id: 4, west_id: 2)
Room.create(map_id: 12, title: 'Death Star', description: "You found a small exhaust port and made your way inside the galaxy's largest death machine", north_id: nil, south_id: 9, east_id: 5, west_id: 3)
Room.create(map_id: 12, title: 'Empire State Building', description: "You see the Empire State Building, how the fuck did that get here?", north_id: nil, south_id: 10, east_id: nil, west_id: 4)
Room.create(map_id: 12, title: 'DBC', description: 'You see a bunch of tired 20 somethings', north_id: 1, south_id: 11, east_id: 7, west_id: nil)
Room.create(map_id: 12, title: 'Keebler Factory', description: 'You see a production line and gorge yourself on EL Fudge', north_id: 2, south_id: 12, east_id: 8, west_id: 6)
Room.create(map_id: 12, title: 'South Side Chicago', description: "If you could die in this game, it'd be here", north_id: 3, south_id: 13, east_id: 9, west_id: 7)
Room.create(map_id: 12, title: 'St. Louis', description: "I wouldn't stay here if I were you.", north_id: 4, south_id: 14, east_id: 10, west_id: 8)
Room.create(map_id: 12, title: 'Hogwarts', description: "I've never read Harry Potter, so I don't know wtf goes here.  Quidditch?", north_id: 5, south_id: 15, east_id: nil, west_id: 9)
Room.create(map_id: 12, title: 'TGRI Headquarters', description: "Making TMNT since day 1", north_id: 6, south_id: nil, east_id: 12, west_id: nil)
Room.create(map_id: 12, title: 'Shipyards', description: 'Yarr Billy!  Check out those schooners!', north_id: 7, south_id: nil, east_id: 13, west_id: 11)
Room.create(map_id: 12, title: 'Mount Doom', description: "Bring your rings.", north_id: 8, south_id: nil, east_id: 14, west_id: 12)
Room.create(map_id: 12, title: 'Fox Den', description: "Pretty foxy up in here.  Can I get a what what?", north_id: 9, south_id: nil, east_id: 15, west_id: 13)
Room.create(map_id: 12, title: 'Elephant Graveyard', description: "I don't know, but you better be prepared.", north_id: 10, south_id: nil, east_id: nil, west_id: 14)
